Repository tutti-tutti/tutti-server, pull requests merged in 2025-03, with the labels that each got.

#246 [BE] Docs 수정
  docs/Review.md
Labels: 📋 문서

#247 [BE] JWT 기능 수정
  src/main/java/com/tutti/server/core/member/application/AuthServiceImpl.java
  src/main/java/com/tutti/server/core/member/jwt/JWTUtil.java
Labels: ✨ BE

#251 release: .github/workflows/dev_tutti-server-web.yml 수정
  .github/workflows/dev_tutti-server-web.yml
  src/main/java/com/tutti/server/core/review/domain/Review.java
Labels: 📦 배포, 🌏 인프라

#255 [BE] data.sql 삭제
  src/main/resources/config/mail.properties
  src/main/resources/data.sql
Labels: 🌏 인프라

#258 [BE] MailConfig 버그 수정
  src/main/java/com/tutti/server/core/config/MailConfig.java
Labels: ♻️ 테스트, ✨ BE

#259 [BE] fix: application.yml 배포 오류 수정
  src/main/resources/application.yml
Labels: 😱 긴급, 📦 배포

#271 [BE] secret/application.yml 수정
  secret/application.yml
Labels: 😱 긴급, 📦 배포

#272 [BE] feat: enum -> String 으로 변환
  src/main/java/com/tutti/server/core/payment/application/PaymentCancelServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/domain/Payment.java
  src/main/java/com/tutti/server/core/payment/domain/PaymentHistory.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentRequest.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentResponse.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentViewResponse.java
Labels: ✨ BE

#256 [BE] 반품 신청
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/domain/Payment.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApi.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApiSpec.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsService.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsServiceImpl.java
  src/main/java/com/tutti/server/core/returns/infrastructure/ReturnsRepository.java
  src/main/java/com/tutti/server/core/returns/payload/ReturnsRequest.java
Labels: ✨ BE

#261 [BE] Faq 관리자 삭제
  src/main/java/com/tutti/server/core/faq/api/FaqAdminApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqAdminApiSpec.java
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminDeleteService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminDeleteServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminServiceImpl.java
  src/main/java/com/tutti/server/core/faq/infrastructure/FaqRepository.java
Labels: ✨ BE

#263 [BE] 판매자 공지사항 생성
  docs/Notice.md
  src/main/java/com/tutti/server/core/notice/domain/Notice.java
Labels: ✨ BE

#275 [BE] feat: 옵션관련 엔티티수정
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/product/domain/Product.java
  src/main/java/com/tutti/server/core/product/domain/ProductItem.java
Labels: ✨ BE

#276 [BE] 약관 조회 기능 수정
  src/main/java/com/tutti/server/core/member/api/TermsConditionsApi.java
  src/main/java/com/tutti/server/core/member/api/TermsConditionsApiSpec.java
  src/main/java/com/tutti/server/core/member/application/TermsConditionsServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/TermsConditionsServiceSpec.java
  src/main/java/com/tutti/server/core/member/domain/TermsConditions.java
  src/main/java/com/tutti/server/core/member/domain/TermsType.java
  src/main/java/com/tutti/server/core/member/infrastructure/TermsConditionsRepository.java
  src/main/java/com/tutti/server/core/member/payload/TermsConditionsResponse.java
Labels: ✨ BE

#279 장바구니 상품 엔티티, DTO 수정
  src/main/java/com/tutti/server/core/cart/domain/CartItem.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemsResponse.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
Labels: ✨ BE

#274 [BE] 반품 상태 조회
  src/main/java/com/tutti/server/core/returns/api/ReturnsApi.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApiSpec.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsService.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsServiceImpl.java
  src/main/java/com/tutti/server/core/returns/payload/ReturnsResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#281 [BE] 주문 엔티티 필드 수정
  src/main/java/com/tutti/server/core/cart/domain/CartItem.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemsResponse.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/domain/OrderItem.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#284 [BE] loadUserById 기능 구현
  src/main/java/com/tutti/server/core/config/SecurityConfig.java
  src/main/java/com/tutti/server/core/member/api/PasswordChangeApi.java
  src/main/java/com/tutti/server/core/member/api/PasswordChangeApiSpec.java
  src/main/java/com/tutti/server/core/member/application/CustomUserDetails.java
  src/main/java/com/tutti/server/core/member/application/CustomUserDetailsService.java
  src/main/java/com/tutti/server/core/member/application/PasswordChangeServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/PasswordChangeServiceSpec.java
  src/main/java/com/tutti/server/core/member/jwt/JWTFilter.java
Labels: ♻️ 테스트, ✨ BE

#289 [AI] 감성분석 모델 배포 적용
  src/main/java/com/tutti/server/core/review/api/SentimentApi.java
Labels: ✨ BE

#291 [BE] feat: 장바구니 조회 기능 수정
  src/main/java/com/tutti/server/core/cart/api/CartApi.java
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/cart/application/CartService.java
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/cart/infrastructure/CartItemRepository.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemsResponse.java
  src/main/java/com/tutti/server/global/config/SwaggerConfig.java
Labels: ✨ BE

#292 [BE] 제미나이 제안 받아드렸다가 복구
  src/main/java/com/tutti/server/core/cart/infrastructure/CartItemRepository.java
Labels: ✨ BE

#288 [BE] AccessToken 재발급 및 Security 예외 처리
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceSpec.java
  src/main/java/com/tutti/server/core/member/jwt/JWTFilter.java
  src/main/java/com/tutti/server/core/member/jwt/JWTUtil.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#290 [BE] 이미 인증된 계정입니다 버그 수정
  src/main/java/com/tutti/server/core/member/application/EmailVerificationServiceImpl.java
Labels: 🐛 버그

#282 [BE] 리뷰 별점 타입 변경
  src/main/java/com/tutti/server/core/review/domain/Review.java
  src/main/java/com/tutti/server/core/review/domain/ReviewLike.java
  src/main/java/com/tutti/server/core/review/payload/request/ReviewCreateRequest.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewCreateResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewDetailResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewResponse.java
Labels: ✨ BE

#283 [BE] feat: 환불 정보 조회
  src/main/java/com/tutti/server/core/refund/api/RefundApi.java
  src/main/java/com/tutti/server/core/refund/api/RefundApiSpec.java
  src/main/java/com/tutti/server/core/refund/application/RefundService.java
  src/main/java/com/tutti/server/core/refund/application/RefundServiceImpl.java
  src/main/java/com/tutti/server/core/refund/infrastructure/RefundRepository.java
  src/main/java/com/tutti/server/core/refund/payload/RefundViewResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#304 [BE] feat: Order 엔티티 수정
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#306 [BE] FAQ 서브카테고리 조회
  src/main/java/com/tutti/server/core/faq/api/FaqApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqCategoryListService.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqMainCategoryListService.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqMainCategoryListServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqSubCategoryListService.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqSubCategoryListServiceImpl.java
  src/main/java/com/tutti/server/core/faq/config/FaqMainCategoryConverter.java
  src/main/java/com/tutti/server/core/faq/domain/FaqMainCategory.java
  src/main/java/com/tutti/server/core/faq/infrastructure/FaqCategoryRepository.java
Labels: 😱 긴급, ✨ BE

#296 [BE] FAQ 목록 조회 수정
  src/main/java/com/tutti/server/core/faq/application/user/FaqListViewServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqSearchListServiceImpl.java
  src/main/java/com/tutti/server/core/faq/infrastructure/FaqRepository.java
Labels: 🛠️ 리팩터링, 😱 긴급, ✨ BE

#308 [BE] FAQ 전체 카테고리 조회
  src/main/java/com/tutti/server/core/faq/api/FaqApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqCategoryListService.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqCategoryListServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqService.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqServiceImpl.java
  src/main/java/com/tutti/server/core/faq/infrastructure/FaqCategoryRepository.java
  src/main/java/com/tutti/server/core/faq/payload/model/FaqCategoryRow.java
  src/main/java/com/tutti/server/core/faq/payload/response/FaqCategoryResponse.java
Labels: ✨ BE

#310 [BE] feat: 1차 테스트 후 수정 사항
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApiSpec.java
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentCancelRequest.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentResponse.java
  src/main/java/com/tutti/server/core/payment/payload/PaymentViewResponse.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApiSpec.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#302 [BE] 리뷰 삭제 기능
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewDeleteService.java
  src/main/java/com/tutti/server/core/review/application/ReviewDeleteServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewDeleteResponse.java
Labels: ✨ BE

#313 [BE] 주문 상세 조회
  docs/Order.md
  src/main/java/com/tutti/server/core/delivery/domain/Delivery.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#319 [BE] FAQ 관리자 사용자 패키지 통합
  src/main/java/com/tutti/server/core/faq/api/FaqAdminApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqAdminApiSpec.java
  src/main/java/com/tutti/server/core/faq/api/FaqApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
Labels: ✨ BE

#318 [BE] feat: Order 엔티티 필드 추가에 따른 DTO 필드 추가
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#322 [BE] feat: CartItemResponse 필드 수정
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemsResponse.java
Labels: ✨ BE

#324 [BE] feat: 주문 삭제 API 기능 구현
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
Labels: ✨ BE

#320 [BE] 리뷰 이 글이 도움이 되었어요 토글 기능
  docs/Review.md
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeService.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewLikeRepository.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewLikeResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#327 [BE] feat: 주문서 생성 API 기능 구현
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderPageRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderPageResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#329 [BE] feat: 주문 API 인가 적용
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#333 [BE] style: 코드 스타일, 필드명 변경
  src/main/java/com/tutti/server/core/cart/api/CartApi.java
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/cart/application/CartService.java
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/cart/infrastructure/CartItemRepository.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemCreateRequest.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderPageRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderPageResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#334 [BE] refactor: CartItemCreateRequest productItemId 중복 검증
  src/main/java/com/tutti/server/core/cart/api/CartApi.java
  src/main/java/com/tutti/server/core/cart/application/CartService.java
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
Labels: ✨ BE

#335 [BE] 리뷰 API 수정
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/api/SentimentApi.java
  src/main/java/com/tutti/server/core/review/api/SentimentApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewCreateServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/SentimentService.java
  src/main/java/com/tutti/server/core/review/application/SentimentServiceImpl.java
  src/main/java/com/tutti/server/core/review/payload/request/SentimentFeedbackRequest.java
  src/main/java/com/tutti/server/core/review/payload/request/SentimentRequest.java
  src/main/java/com/tutti/server/core/review/payload/response/SentimentFeedbackResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/SentimentResponse.java
Labels: ✨ BE

#325 [BE] feat: 결제 인가 추가
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApiSpec.java
  src/main/java/com/tutti/server/core/payment/application/PaymentCancelService.java
  src/main/java/com/tutti/server/core/payment/application/PaymentCancelServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/PaymentService.java
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/PaymentViewService.java
  src/main/java/com/tutti/server/core/payment/application/PaymentViewServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/TossPaymentService.java
  src/main/java/com/tutti/server/core/payment/domain/Payment.java
  src/main/java/com/tutti/server/core/payment/infrastructure/PaymentRepository.java
  src/main/java/com/tutti/server/core/payment/payload/TossPaymentsCancelResponse.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentCancelRequest.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentConfirmRequest.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentRequest.java
  src/main/java/com/tutti/server/core/payment/payload/request/TossPaymentsCancelRequest.java
  src/main/java/com/tutti/server/core/payment/payload/response/ParsedTossApiResponse.java
  src/main/java/com/tutti/server/core/payment/payload/response/PaymentConfirmResponse.java
  src/main/java/com/tutti/server/core/payment/payload/response/PaymentResponse.java
  src/main/java/com/tutti/server/core/payment/payload/response/PaymentViewResponse.java
  src/main/java/com/tutti/server/core/payment/payload/response/TossPaymentsCancelResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#339 Be/feat/338 refund authorization
  src/main/java/com/tutti/server/core/refund/api/RefundApi.java
  src/main/java/com/tutti/server/core/refund/api/RefundApiSpec.java
  src/main/java/com/tutti/server/core/refund/application/RefundService.java
  src/main/java/com/tutti/server/core/refund/application/RefundServiceImpl.java
Labels: ✨ BE

#337 refactor: CartItem, Order 세밀한 예외처리
  docs/Order.md
  src/main/java/com/tutti/server/core/cart/application/CartService.java
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/cart/infrastructure/CartItemRepository.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
Labels: 🛠️ 리팩터링, ✨ BE

#342 [BE] FAQ 목록 조회 방식 수정
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
  src/main/java/com/tutti/server/core/faq/application/user/FaqListViewServiceImpl.java
  src/main/java/com/tutti/server/core/faq/infrastructure/FaqRepository.java
  src/main/java/com/tutti/server/core/faq/payload/request/FaqListRequest.java
Labels: ✨ BE

#340 [BE] 리뷰 로그인한 사용자 좋아요 여부 표시
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewDetailService.java
  src/main/java/com/tutti/server/core/review/application/ReviewDetailServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewDetailResponse.java
Labels: ✨ BE

#344 [BE] feat: 환불요청(결제취소), 환불 조회 인가 추가
  src/main/java/com/tutti/server/core/refund/api/RefundApi.java
  src/main/java/com/tutti/server/core/refund/application/RefundServiceImpl.java
Labels: ✨ BE

#346 [BE] feat: 주문 생성 API와 결제 생성 API 합치기
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/domain/OrderStatus.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderHistoryRepository.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApiSpec.java
  src/main/java/com/tutti/server/core/payment/application/PaymentCancelServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/TossPaymentService.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentRequest.java
Labels: ✨ BE

#305 [BE] feat: 상품 카테고리 전체 목록조회
  src/main/java/com/tutti/server/core/product/api/CategoryApi.java
  src/main/java/com/tutti/server/core/product/api/CategoryApiSpec.java
  src/main/java/com/tutti/server/core/product/application/CategoryService.java
  src/main/java/com/tutti/server/core/product/application/CategoryServiceImpl.java
  src/main/java/com/tutti/server/core/product/infrastructure/CategoryRepository.java
  src/main/java/com/tutti/server/core/product/payload/response/CategoryResponse.java
Labels: ✨ BE

#355 feat: 스웨거 관련 리팩토링
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/api/LogoutApi.java
  src/main/java/com/tutti/server/core/member/api/LogoutApiSpec.java
  src/main/java/com/tutti/server/core/member/api/MemberApi.java
  src/main/java/com/tutti/server/core/member/api/MemberApiSpec.java
  src/main/java/com/tutti/server/core/member/api/PasswordApi.java
  src/main/java/com/tutti/server/core/member/api/PasswordApiSpec.java
  src/main/java/com/tutti/server/core/member/api/PasswordResetApi.java
  src/main/java/com/tutti/server/core/member/api/PasswordResetApiSpec.java
  src/main/java/com/tutti/server/core/member/application/LogoutServiceImpl.java
Labels: ✨ BE

#356 [BE] feat : 반품 인가 적용 완료
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentCancelRequest.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApi.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApiSpec.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsService.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsServiceImpl.java
Labels: ✨ BE

#357 [BE] style: 메서드명, 코드 위치 변경
  src/main/java/com/tutti/server/core/cart/api/CartApi.java
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/cart/application/CartService.java
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemsCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemResponse.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
Labels: ✨ BE

#360 [BE] feat: 주문 상세 조회 기능에 배송 관련 정보 적용하기
  docs/Order.md
  src/main/java/com/tutti/server/core/delivery/domain/Carrier.java
  src/main/java/com/tutti/server/core/delivery/domain/Delivery.java
  src/main/java/com/tutti/server/core/delivery/infrastructure/DeliveryRepository.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/OrderItem.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#359 [BE] 리뷰 상품 연결
  src/main/java/com/tutti/server/core/order/infrastructure/OrderItemRepository.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewCreateService.java
  src/main/java/com/tutti/server/core/review/application/ReviewCreateServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/domain/Review.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewRepository.java
  src/main/java/com/tutti/server/core/review/payload/request/ReviewCreateRequest.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewCreateResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewDetailResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewResponse.java
Labels: ✨ BE

#358 [BE] 회원 탈퇴
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceSpec.java
  src/main/java/com/tutti/server/core/member/domain/Member.java
  src/main/java/com/tutti/server/core/member/payload/WithdrawalRequest.java
Labels: ✨ BE

#361 [BE] 마이페이지
  src/main/java/com/tutti/server/core/member/api/MypageApi.java
  src/main/java/com/tutti/server/core/member/api/MypageApiSpec.java
  src/main/java/com/tutti/server/core/member/application/MypageServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/MypageServiceSpec.java
  src/main/java/com/tutti/server/core/member/domain/Member.java
  src/main/java/com/tutti/server/core/member/payload/MemberResponse.java
  src/main/java/com/tutti/server/core/member/payload/UpdateMemberRequest.java
Labels: ✨ BE

#374 [BE] 마이페이지 리팩토링
  src/main/java/com/tutti/server/core/member/api/MypageApi.java
  src/main/java/com/tutti/server/core/member/api/MypageApiSpec.java
  src/main/java/com/tutti/server/core/member/jwt/JWTUtil.java
Labels: 🛠️ 리팩터링, ⏸️안 급함

#370 [BE] feat: 상품 상세 서비스
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductItemRepository.java
  src/main/java/com/tutti/server/core/product/infrastructure/SkuRepository.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductItemResponse.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductOptionResponse.java
  src/main/java/com/tutti/server/core/stock/domain/Sku.java
  src/main/java/com/tutti/server/core/store/infrastructure/StoreRepository.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#378 [BE] feat: CartItemResponse 체크값 필드 추가
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemResponse.java
  src/main/java/com/tutti/server/global/config/FaqAsyncConfig.java
  src/main/java/com/tutti/server/global/config/LocalImageStorageConfig.java
  src/main/java/com/tutti/server/global/config/MailConfig.java
  src/main/java/com/tutti/server/global/config/SecurityConfig.java
Labels: ✨ BE

#380 [BE] Feat: 요청값에 주문ID 추가
  src/main/java/com/tutti/server/core/order/infrastructure/OrderItemRepository.java
  src/main/java/com/tutti/server/core/review/application/ReviewCreateServiceImpl.java
  src/main/java/com/tutti/server/core/review/payload/request/ReviewCreateRequest.java
Labels: ✨ BE

#383 [BE] Feat: 리뷰 감성분석 긍정률
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/application/SentimentPositiveService.java
  src/main/java/com/tutti/server/core/review/application/SentimentPositiveServiceImpl.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewRepository.java
  src/main/java/com/tutti/server/core/review/payload/response/SentimentPositiveAvgResponse.java
Labels: ✨ BE

#385 [BE] Refactor: 리뷰 개인 작성 목록 조회 요청값 변경
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewMyListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewMyListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewRepository.java
  src/main/java/com/tutti/server/core/review/payload/request/ReviewMyListRequest.java
Labels: 🛠️ 리팩터링, ✨ BE

#387 [BE] 최근 본 상품 조회, 삭제
  src/main/java/com/tutti/server/core/member/api/MypageApi.java
  src/main/java/com/tutti/server/core/member/api/ViewedProductApi.java
  src/main/java/com/tutti/server/core/member/api/ViewedProductApiSpec.java
  src/main/java/com/tutti/server/core/member/application/ViewedProductServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/ViewedProductServiceSpec.java
  src/main/java/com/tutti/server/core/member/infrastructure/ViewedProductRepository.java
  src/main/java/com/tutti/server/core/member/utils/TokenExtractor.java
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
Labels: ✨ BE

#389 [BE] 어노테이션 정리
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/api/MypageApi.java
  src/main/java/com/tutti/server/core/member/api/MypageApiSpec.java
  src/main/java/com/tutti/server/core/member/api/PasswordApi.java
  src/main/java/com/tutti/server/core/member/api/PasswordApiSpec.java
Labels: ✨ BE

#391 [BE] 패스워드 기능 재정비
  src/main/java/com/tutti/server/core/member/api/EmailVerificationApi.java
  src/main/java/com/tutti/server/core/member/api/EmailVerificationApiSpec.java
  src/main/java/com/tutti/server/core/member/api/PasswordApi.java
  src/main/java/com/tutti/server/core/member/application/EmailVerificationServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/EmailVerificationServiceSpec.java
  src/main/java/com/tutti/server/core/member/application/PasswordResetServiceImpl.java
  src/main/java/com/tutti/server/core/member/domain/VerificationCode.java
  src/main/java/com/tutti/server/core/member/payload/EmailVerificationConfirmRequest.java
  src/main/java/com/tutti/server/core/member/payload/EmailVerificationSendRequest.java
  src/main/java/com/tutti/server/core/member/payload/PasswordResetRequest.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#393 [BE] feat: payments 응답값 추가
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
  src/main/java/com/tutti/server/core/payment/api/PaymentApiSpec.java
Labels: ✨ BE

#397 [BE] Refactor: 리뷰 목록 조회 API 분리
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewLatestListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewLatestListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewMyListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewRatingListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewRatingListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewRepository.java
  src/main/java/com/tutti/server/core/review/payload/request/LatestReviewCursor.java
  src/main/java/com/tutti/server/core/review/payload/request/LikeReviewCursor.java
  src/main/java/com/tutti/server/core/review/payload/request/RatingReviewCursor.java
  src/main/java/com/tutti/server/core/review/payload/response/LatestReviewCursorResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/LatestReviewListResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/LikeReviewCursorResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/LikeReviewListResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/RatingReviewCursorResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/RatingReviewListResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewListResponse.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewMyListResponse.java
Labels: 🛠️ 리팩터링, 😱 긴급, 🐛 버그, ✨ BE

#395 [BE] fix: 가격 로직 변경 및 재고 반영
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/domain/ProductItem.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductItemResponse.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductOptionResponse.java
  src/main/java/com/tutti/server/core/sku/domain/Sku.java
  src/main/java/com/tutti/server/core/sku/domain/SkuHistory.java
  src/main/java/com/tutti/server/core/sku/domain/SkuHistoryType.java
  src/main/java/com/tutti/server/core/sku/infrastructure/SkuRepository.java
  src/main/java/com/tutti/server/core/stock/domain/Sku.java
  src/main/java/com/tutti/server/core/stock/domain/SkuHistoryType.java
  src/main/java/com/tutti/server/core/store/infrastructure/StoreRepository.java
  src/test/java/com/tutti/server/core/product/application/ProductServiceImplTest.java
Labels: ♻️ 테스트, ✨ BE

#398 [BE] 소셜 로그인 기능 + 토큰 발급까지
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceSpec.java
  src/main/java/com/tutti/server/core/member/application/GoogleTokenVerifier.java
  src/main/java/com/tutti/server/core/member/application/NaverTokenVerifier.java
  src/main/java/com/tutti/server/core/member/application/SocialTokenVerifier.java
  src/main/java/com/tutti/server/core/member/payload/SocialLoginRequest.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#399 [BE] feat: 결제 api 수정
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
Labels: 🐛 버그

#402 [BE] Feat: 리뷰 삭제 인증 적용
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewDeleteService.java
  src/main/java/com/tutti/server/core/review/application/ReviewDeleteServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#404 [BE] FAQ 관리자 인증 적용
  src/main/java/com/tutti/server/core/faq/api/FaqApi.java
  src/main/java/com/tutti/server/core/faq/api/FaqApiSpec.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminCreateService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminCreateServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminDeleteService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminDeleteServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminServiceImpl.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminUpdateService.java
  src/main/java/com/tutti/server/core/faq/application/admin/FaqAdminUpdateServiceImpl.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE, ⏸️안 급함

#405 [BE] 소셜 회원 탈퇴
  src/main/java/com/tutti/server/core/member/api/AuthApi.java
  src/main/java/com/tutti/server/core/member/api/AuthApiSpec.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/AuthServiceSpec.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#408 [BE] 결제 승인 api 접근 확인 로깅
  src/main/java/com/tutti/server/core/payment/api/PaymentApi.java
Labels: ♻️ 테스트

#409 [BE] 로그서버 연동 테스트
  build.gradle
  src/main/java/com/tutti/server/core/support/logging/ControllerLoggingAspect.java
  src/main/resources/logback-spring.xml
Labels: ♻️ 테스트, 🌞환경설정

#410 [BE] Feat: 리뷰 목록 좋아여 여부 추가
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
  src/main/java/com/tutti/server/core/review/api/ReviewApiSpec.java
  src/main/java/com/tutti/server/core/review/application/ReviewLatestListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewLatestListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewLikeListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewRatingListService.java
  src/main/java/com/tutti/server/core/review/application/ReviewRatingListServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewRatingServiceImpl.java
  src/main/java/com/tutti/server/core/review/application/ReviewService.java
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewLikeRepository.java
  src/main/java/com/tutti/server/core/review/payload/response/ReviewResponse.java
  src/main/java/com/tutti/server/core/review/utils/ReviewLike.java
Labels: ✨ BE

#412 [BE] feat: 결제 토스페이먼츠 로그 추가
  src/main/java/com/tutti/server/core/payment/application/TossPaymentService.java
Labels: ♻️ 테스트

#415 [BE] feat: 반품 swagger 추가
  src/main/java/com/tutti/server/core/returns/api/ReturnsApi.java
Labels: ✨ BE

#417 [BE] Error: 리뷰 NPE 처리
  src/main/java/com/tutti/server/core/review/api/ReviewApi.java
Labels: 🐛 버그, ✨ BE

#418 [BE] feat: 도착예정일 필드 추가
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
Labels: ✨ BE

#419 [BE] fix: OrderItemRequest toEntity() 보완
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
Labels: 🐛 버그, ✨ BE
