Repository tutti-tutti/tutti-server, pull requests merged in 2025-05, with the labels that each got.

#472 [BE] Tags, Product Tags 엔티티 생성
  src/main/java/com/tutti/server/core/product/domain/Product.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductItemResponse.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
  src/main/java/com/tutti/server/core/tag/domain/ProductTag.java
  src/main/java/com/tutti/server/core/tag/domain/Tag.java
  src/main/java/com/tutti/server/core/tag/infrastructure/ProductTagRepository.java
Labels: ✨ BE

#473 회원 행동 로그 좋아요 빼고 기록하기
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/MemberBehaviorLogService.java
  src/main/java/com/tutti/server/core/member/application/MemberBehaviorLogServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/ViewedProductServiceImpl.java
  src/main/java/com/tutti/server/core/member/domain/BehaviorType.java
  src/main/java/com/tutti/server/core/member/domain/MemberBehaviorLog.java
  src/main/java/com/tutti/server/core/member/infrastructure/MemberBehaviorLogRepository.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
Labels: ✨ BE

#468 feat : 관심사 관련 엔티티 만들기 1단계
  src/main/java/com/tutti/server/core/member/domain/Interest.java
  src/main/java/com/tutti/server/core/member/domain/InterestType.java
  src/main/java/com/tutti/server/core/member/domain/MemberInterestMapping.java
Labels: ✨ BE

#477 release: workflow 파일 수정
  .github/workflows/deploy.yml
Labels: 📦 배포, 🌏 인프라, ✨ BE

#478 Update deploy.yml
  .github/workflows/deploy.yml
Labels: 😱 긴급, 📦 배포

#479 Update deploy.yml
  .github/workflows/deploy.yml
Labels: 😱 긴급, 📦 배포

#481 [BE] refactor: 상품 데이터에 태깅
  src/main/java/com/tutti/server/core/product/payload/response/ProductItemResponse.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductResponse.java
  src/main/java/com/tutti/server/core/tag/domain/ProductTag.java
  src/main/java/com/tutti/server/core/tag/payload/response/ProductTagResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#482 [BE] refactor: tag Id 추출 리팩토링
  src/main/java/com/tutti/server/core/product/payload/response/ProductItemResponse.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#471 feat: 좋아요 기능 rud
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/domain/Product.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductLikeRepository.java
Labels: ✨ BE

#484 feat: 태그 스코어링까지(회원가입, 회원로그)
  src/main/java/com/tutti/server/core/member/application/MemberBehaviorLogServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/MemberServiceImpl.java
  src/main/java/com/tutti/server/core/member/domain/BehaviorType.java
  src/main/java/com/tutti/server/core/member/infrastructure/MemberCategoryScoreRepository.java
  src/main/java/com/tutti/server/core/member/payload/SignupRequest.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/domain/Product.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductCategoryMapRepository.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductCategoryRepository.java
Labels: ✨ BE

#487 [BE] docs: gitignore에 *sql 추가
  .gitignore
Labels: 📋 문서

#486 feat: CRM 회원 추천 상품 API
  src/main/java/com/tutti/server/core/member/application/MemberBehaviorLogServiceImpl.java
  src/main/java/com/tutti/server/core/member/application/MemberServiceImpl.java
  src/main/java/com/tutti/server/core/member/domain/MemberTagScore.java
  src/main/java/com/tutti/server/core/member/domain/ShoppingValueType.java
  src/main/java/com/tutti/server/core/member/infrastructure/MemberCategoryScoreRepository.java
  src/main/java/com/tutti/server/core/member/infrastructure/MemberTagScoreRepository.java
  src/main/java/com/tutti/server/core/member/payload/SignupRequest.java
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductRepository.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
  src/main/java/com/tutti/server/core/tag/infrastructure/TagRepository.java
Labels: ✨ BE
