Repository tutti-tutti/tutti-server, pull requests merged in 2025-04, with the labels that each got.

#421 [BE]: Error: 페이징 처리 오류 수정
  src/main/java/com/tutti/server/core/review/infrastructure/ReviewRepository.java
Labels: 🐛 버그, ✨ BE

#422 [BE] feat: 상품리스트 무한스크롤
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/domain/Product.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductRepository.java
  src/main/java/com/tutti/server/core/product/payload/response/ProductSliceResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: ✨ BE

#424 [BE] feat: 상품 추천 리스트 임시
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductRepository.java
Labels: ✨ BE

#426 feat: 주문 내역 전체 조회 최신순으로
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
Labels: ✨ BE

#430 [BE] be/feat/429 change get order response
  src/main/java/com/tutti/server/core/order/domain/OrderItem.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#431 [BE] chore: OrderDetailResponse 필드명 수정
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
Labels: ✨ BE

#437 [BE] refactor: 주문 응답 DTO 필드 수정
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderPageRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderPageResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#440 [BE] refactor: 주문 내역 페이징 처리
  src/main/java/com/tutti/server/core/delivery/domain/DeliveryHistory.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/OrderHistory.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: ✨ BE

#441 [BE] Be/refactor/439 order number replace
  docs/Order.md
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
  src/main/java/com/tutti/server/core/payment/application/PaymentCancelServiceImpl.java
  src/main/java/com/tutti/server/core/payment/application/PaymentServiceImpl.java
  src/main/java/com/tutti/server/core/payment/domain/Payment.java
  src/main/java/com/tutti/server/core/payment/infrastructure/PaymentRepository.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentCancelRequest.java
  src/main/java/com/tutti/server/core/payment/payload/request/PaymentRequest.java
  src/main/java/com/tutti/server/core/payment/payload/response/PaymentResponse.java
  src/main/java/com/tutti/server/core/returns/application/ReturnsServiceImpl.java
Labels: 🛠️ 리팩터링, ✨ BE

#445 [BE] refactor: 장바구니 응답값 수정 및 동일 상품 추가 로직 변경
  docs/Cart.md
  docs/Order.md
  src/main/java/com/tutti/server/core/cart/application/CartServiceImpl.java
  src/main/java/com/tutti/server/core/cart/domain/CartItem.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemsCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderPageResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#449 [BE] feat: 상품검색 리스트
  src/main/java/com/tutti/server/core/product/api/ProductApi.java
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/application/ProductService.java
  src/main/java/com/tutti/server/core/product/application/ProductServiceImpl.java
  src/main/java/com/tutti/server/core/product/infrastructure/ProductRepository.java
  src/main/java/com/tutti/server/core/product/payload/request/SearchRequest.java
Labels: ✨ BE

#454 [BE] 검색 오타수정
  src/main/java/com/tutti/server/core/product/api/ProductApiSpec.java
  src/main/java/com/tutti/server/core/product/payload/request/SearchRequest.java
Labels: ✨ BE

#455 [BE] refactor: 정적스크롤 -> 무한스크롤 변경
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderRepository.java
  src/main/java/com/tutti/server/core/order/payload/response/CursorBasedOrdersResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderSheetResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#457 [BE] refactor: 장바구니 코드 포맷 정리
  src/main/java/com/tutti/server/core/cart/api/CartApi.java
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/cart/domain/CartItem.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemsCreateRequest.java
  src/main/java/com/tutti/server/core/cart/payload/response/CartItemResponse.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionCode.java
  src/main/java/com/tutti/server/core/support/exception/ExceptionType.java
Labels: 🛠️ 리팩터링, ✨ BE

#459 [BE] refactor: 주문 코드 포맷 정리
  src/main/java/com/tutti/server/core/cart/api/CartApiSpec.java
  src/main/java/com/tutti/server/core/cart/payload/request/CartItemsCreateRequest.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderItemRequest.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderSheetRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/CursorBasedOrdersResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
Labels: 🛠️ 리팩터링, ✨ BE

#460 [BE] refactor: 환불 엔드포인트 수정
  src/main/java/com/tutti/server/core/refund/api/RefundApi.java
  src/main/java/com/tutti/server/core/refund/api/RefundApiSpec.java
  src/main/java/com/tutti/server/core/returns/api/ReturnsApiSpec.java
Labels: 🛠️ 리팩터링, ✨ BE

#462 [BE] refactor: 배송 엔티티 필드 변경
  src/main/java/com/tutti/server/core/delivery/domain/Carrier.java
  src/main/java/com/tutti/server/core/delivery/domain/Delivery.java
  src/main/java/com/tutti/server/core/order/payload/request/OrderCreateRequest.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/returns/domain/Returns.java
  src/main/java/com/tutti/server/core/support/entity/BaseEntity.java
Labels: 🛠️ 리팩터링, ✨ BE

#463 [BE] refactor: 주문서 작성 페이지 메서드명 변경
  src/main/java/com/tutti/server/core/cart/domain/CartItem.java
  src/main/java/com/tutti/server/core/order/api/OrderApi.java
  src/main/java/com/tutti/server/core/order/api/OrderApiSpec.java
  src/main/java/com/tutti/server/core/order/application/OrderService.java
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/Order.java
  src/main/java/com/tutti/server/core/order/domain/OrderItem.java
Labels: 🛠️ 리팩터링, ✨ BE

#465 [BE] refactor: 주문 내역에서 리뷰 작성여부 데이터가 필요해요
  src/main/java/com/tutti/server/core/order/application/OrderServiceImpl.java
  src/main/java/com/tutti/server/core/order/domain/OrderItem.java
  src/main/java/com/tutti/server/core/order/infrastructure/OrderItemRepository.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderItemResponse.java
  src/main/java/com/tutti/server/core/review/application/ReviewCreateServiceImpl.java
Labels: 🛠️ 리팩터링, ✨ BE

#466 [BE] chore: DTO 어노테이션 수정
  src/main/java/com/tutti/server/core/order/payload/response/OrderDetailResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderResponse.java
  src/main/java/com/tutti/server/core/order/payload/response/OrderSheetResponse.java
Labels: 📋 문서, ✨ BE

#469 feat: 카테고리 스코어링 엔티티 만들기
  src/main/java/com/tutti/server/core/member/domain/MemberCategoryScore.java
Labels: ✨ BE
